### ISSUE TITLE
Warning! Sampled labelled that are outside the thematic map area or inside the no data values:

### ISSUE THREAD

**Issue by MarcioDDCF** [SMByC/AcATaMa#18] opened 2023-06-29 05:23 UTC
Hi, Just experimenting with your plug in and I really like the GUI and hope you can help me fix my issue. 

I've run a 200 point Simple Random Sample over a tif with 2 classes, 0 and 1. 

When I get to the accuracy results, I get the warning (of the title) and essentially all of the classes that were marked 0 are not included in the accuracy assessment analysis and report.

Any chance this is a known issue and I might have just done the set up wrong? Should I perhaps re-classify the 0 values to another integer number in the raster..

![image](https://github.com/SMByC/AcATaMa/assets/135607519/c80cbec7-6503-45ae-aad3-a69be7cc911c)

TIA,
m

**Comment by XavierCLL** [comment] 2023-06-29 17:06
Hi @MarcioDDCF 

That "Warning" tell you 2 possible problems when Acatama tries to compute the accuracy assessment: 1) when the samples are outside the thematic, and that only happens when you have generated it with another app and it does not match with the thematic. 2) some of the samples are (and generated) in nodata values in the thematic map.

I think, your issue is the second one, so: if you want to sample and evaluate in the 0 values, then 0 values are important for you, and they shouldn't be as a nodata values! Then: unset the nodata in your thematic. It should solve that warning issue and accuracy assessment results.

Let me know if that helps
Xavier

**Comment by MarcioDDCF** [comment] 2023-06-29 23:16
Hi Xavier,

Thanks for the reply. To clarify, all of the sampling was done in the GUI and sampled within a raster that had values of 0 or 1. It would appear that 0 is being interpreted as no-data, even though I have a no-data value set within the tool as something else. 

Will try to re-run the GUI with a re-classified raster of (1,2) instead of (0,1). 

cheers

**Comment by XavierCLL** [comment] 2023-06-30 00:13
Having a thematic with values between 0 and 1 should not be a problem, I'm almost sure that your image has 0 as nodata check the properties: do right click > properties > information > bands

You can also check how Acatama recognizes the nodata for your Thematic here:
![image](https://github.com/SMByC/AcATaMa/assets/11801453/50b27056-8bd4-4db7-a6a6-8984f8e2ade0)

If it is zero, you can just clean that box, and try again. But the best it unset the nodata, you can do that in Qgis but for me, the easy way is in the terminal:

```bash
gdal_edit.py image.tif -unsetnodata
```

**Comment by MarcioDDCF** [comment] 2023-06-30 00:16
Hmm.. Thanks for helping me think through this..

But, the no-data value matched what I put in to that box.

![image](https://github.com/SMByC/AcATaMa/assets/135607519/05140c99-9f49-47c7-8dfd-6db351f8ed1c)

**Comment by XavierCLL** [comment] 2023-06-30 00:19
Yeah the nodata box should be -9999, that is ok, so the problem is different and you don't need to unset the nodata. Then, are you sure that the samples generated in the 0 and 1 values? did you generate the samples with the thematic or with another file? could you show me the configuration of the sampling tab?

**Comment by MarcioDDCF** [comment] 2023-06-30 00:23
Sure, let me load up the one that I saved (this happened 2 times on 2 similarly classified images)

![image](https://github.com/SMByC/AcATaMa/assets/135607519/7f9c375c-50c6-43c2-a09a-00476135ea04)

![image](https://github.com/SMByC/AcATaMa/assets/135607519/6d2fae72-db99-4a36-bf99-bcfdfc7f3bac)

![image](https://github.com/SMByC/AcATaMa/assets/135607519/2bc2af2c-74c8-468c-9abb-f3be00a7c054)

![image](https://github.com/SMByC/AcATaMa/assets/135607519/226ba6e6-565b-4c04-b763-52d52b0686d2)

**Comment by XavierCLL** [comment] 2023-06-30 00:37
Ok perfect, now I understand your issue:

When you do a simple random sampling, Acatama will generate the samples in the whole thematic (it doesn't matter the pixel values). What you need to do is a post-stratified the simple random sampling, which means that the simple random sampling only accepts the samples into specific values of your thematic file (in your case, only for 0 and 1). Something like this:
![image](https://github.com/SMByC/AcATaMa/assets/11801453/450816f7-0fe7-467e-9f74-fc471c77a07a)

**Comment by MarcioDDCF** [comment] 2023-06-30 02:14
Unfortunately, got the same issue...


![image](https://github.com/SMByC/AcATaMa/assets/135607519/fa8e3df7-d563-4012-8a4b-7af42a568fe8)

![image](https://github.com/SMByC/AcATaMa/assets/135607519/8214962d-8b62-4228-869c-22d9d9f21fa4)

**Comment by XavierCLL** [comment] 2023-06-30 02:45
that is weird, maybe the warning is showing another think but I want to test what is happening. Could you please send me the thematic, sampling file and acatama yml config file? to test it locally

**Comment by MarcioDDCF** [comment] 2023-06-30 04:27
Not sure how to send you these files. They are quite large.

Either way, I've found by re-running my segmentation algos as (1,2) instead of (0,1) I am able to get a working output. Thanks for your help.

**Comment by XavierCLL** [comment] 2023-06-30 06:23
Glad to help, and good to know that you were able to find a way to avoid those warnings and get your results. I'm closing this but be free to open it again if you need it.

**Closed by XavierCLL** 2023-06-30 06:23 UTC
Labels: question
